### ISSUE TITLE
Email notifications fail due to permissions error on template files

### ISSUE THREAD

**Issue by timtoumba** [YunoHost-Apps/jellyseerr_ynh#37]
### Describe the bug

The installation of Jellyseerr on YunoHost does not seem to correctly set the ownership or permissions for files in the `/var/www/jellyseerr/dist` directory. As a result, Jellyseerr fails to access its template files, causing errors such as:

```
EACCES: permission denied, open '/var/www/jellyseerr/dist/templates/email/media-request/subject.pug'
```

It appears the `dist` directory and its contents are not owned by the Jellyseerr system user, preventing the application from functioning properly.

---

### Context

- **Hardware:** VPS bought online
- **YunoHost version:** 11.3.0.2
- **I have access to my server:** Through SSH and through the webadmin
- **Are you in a special context or did you perform some particular tweaking on your YunoHost instance?** No
- **Using, or trying to install package version/branch:** Jellyseerr version installed via the YunoHost app catalog.
- **If upgrading, current package version:** 2.1.0~ynh1.

---

### Steps to reproduce

1. Install Jellyseerr on YunoHost via the webadmin or CLI:
2. Configure Jellyseerr to send an email notification.
3. Trigger an event that requires sending an email (e.g., a media request).
4. Check the logs or the interface, and observe the error indicating a permission issue for accessing files in the `/var/www/jellyseerr/dist` directory.

---

### Expected behavior

The installation script should ensure that all files under `/var/www/jellyseerr` are owned by the appropriate system user (likely `jellyseerr`) with correct permissions, allowing the application to function without issues.

---

### Logs

Here’s an example of the error logged by Jellyseerr:
```
EACCES: permission denied, open '/var/www/jellyseerr/dist/templates/email/media-request/subject.pug'
```

---

### Additional Information

This issue can likely be resolved by updating the installation script to set the correct ownership recursively after deploying the application files. For example:
```bash
chown -R jellyseerr:jellyseerr /var/www/jellyseerr
```

Let me know if you need further details or testing.

**Comment by Thovi98** [comment]
Indeed, I remember having this issue but forgot to update the script… Thanks for notifying! :)
