### ISSUE TITLE
Cannot install Jellyseer on Raspberry Pi 4

### ISSUE THREAD

**Issue by 0x346e3730** [YunoHost-Apps/jellyseerr_ynh#5]
### Describe the bug

Cannot install Jellyseerr

### Context

- Hardware: Raspberry Pi 4
- YunoHost version: 11.2.3
- I have access to my server: Through SSH & through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: jellyseerr_ynh

### Steps to reproduce

Tried to install Jellyseer trough the Admin Panel

### Expected behavior

The installation to complete

### Logs

https://paste.yunohost.org/raw/ijofoqevir

**Comment by Thovi98** [comment]
Strange, looks more like a permission issue although the script is run as root…
Did you try again?

**Comment by tr1p0p** [comment]
It work for me on raspebrry pi 4 arm64

**Comment by Thovi98** [comment]
Thanks, I will close this as @0x346e3730 didn't answer. Feel free to reopen of needed.
